### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by Coreykennedy1993** [Summaw/BattleNet-Account-Generator#1]
Help with battlenet generator? can you make a short tutorial. not sure what im doing wrong.

**Comment by Summaw** [comment]
> Help with battlenet generator? can you make a short tutorial. not sure what im doing wrong. 

What seems to be the problem?l

**Comment by Coreykennedy1993** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/125862982/220054923-ba890c79-2d9c-4a16-ae09-fef3c0e450f9.png)
![Screenshot (4)](https://user-images.githubusercontent.com/125862982/220054937-f0bcfed8-948e-48d2-8712-e986e4a8eb72.png)

i followed all the steps. Am i missing something? probabl
![Screenshot (6)](https://user-images.githubusercontent.com/125862982/220055311-3771556a-ac71-4aa2-927e-650c0c50dfc2.png)
y doing something wrong

**Comment by Summaw** [comment]
> ![Screenshot (5)](https://user-images.githubusercontent.com/125862982/220054923-ba890c79-2d9c-4a16-ae09-fef3c0e450f9.png)
> 
> ![Screenshot (4)](https://user-images.githubusercontent.com/125862982/220054937-f0bcfed8-948e-48d2-8712-e986e4a8eb72.png)
> 
> 
> 
> i followed all the steps. Am i missing something? probabl
> 
> ![Screenshot (6)](https://user-images.githubusercontent.com/125862982/220055311-3771556a-ac71-4aa2-927e-650c0c50dfc2.png)
> 
> y doing something wrong

So temp-mail-fuck used to be a npm package but it seems it has been removed I will update with new steps on what to do.

**Comment by Coreykennedy1993** [comment]
thank you!

**Comment by Coreykennedy1993** [comment]
will this generate accounts for  me? I have v auth for cookies for battlenet

**Comment by Summaw** [comment]
> thank you!

Hey, I will upload the files for temp-mail-fuck here shortly.

**Comment by Dupetonotaz** [comment]
yo where i get the informations about the account email name phone everything?

**Comment by Summaw** [comment]
> yo where I get the information's about the account email name phone everything?

The information for the accounts is stored in created.txt, you can login to the account later to access the account information. There is no phone verification on this program so you will need to find something else that does or you will need to do that manually. Maybe I could implement something in the future when this hits 20 stars.
