### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by ajman6969** [Summaw/BattleNet-Account-Generator#3]
hello, i dont know how to do this i did the first step but then iam lost

**Comment by nate762556** [comment]
i was looking for some help on installing this i downloaded node and brave but i don't know where to go or what to do after reading the instructions if i could get an email or a simple respond back that'll be nice thanks

**Comment by Summaw** [comment]
> i was looking for some help on installing this i downloaded node and brave but i don't know where to go or what to do after reading the instructions if i could get an email or a simple respond back that'll be nice thanks

If you followed all of the instructions then you should be able to simply run the application.
